stages:
  - test
  - docker

test:
  stage: test
  image: python:3.11-slim
  script:
    - pip install -r requirements.txt
    - PYTHONPATH="$CI_PROJECT_DIR" pytest tests/ -v --junitxml=test-results.xml --cov=. --cov-report=xml --cov-report=html

build_and_push:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    IMAGE_NAME: "$DOCKERHUB_USERNAME/gitlab-ci-demo"
    TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$TAG .
    - docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$TAG
    - docker push $IMAGE_NAME:latest
  only:
    - main